apiVersion: v1
kind: PersistentVolume
metadata:
  name: netflix-db-pv
spec:
  storageClassName: netflix-manual
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "/tmp/netflix-db-data"